# Setup
title:               Simon
tagline:             'A Hardware Guy 🌄🌃'
description:         'A blog archiving my thoughts and projects.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Shengzhe LYU (Simon)
  url:               https://twitter.com/mdo
  email:             shengzhe.lyu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
