# Setup
title:               Simon
tagline:             'A Hardware Guy 🌄🌃'
description:         'A place to share my thoughts.'
domain:              simon6501.github.io
url:                 https://simon6501.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Simon
  url:               https://github.com/simon6501
  email:             shengzhe.lyu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Starting time
start_time:          '2024-04-17T00:00:00Z'