# Setup
title:               Simon
tagline:             'A Hardware guy 🌄🌃'
description:         'Ready to go.'
domain:              simon6501.github.io
url:                 https://simon6501.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Simon
  url:               https://github.com/simon6501
  email:             shengzhe.lyu@gmail.com

# Remote theme
remote_theme: jekyll/minima

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Custom vars
version:             1.1.0
google_analytics_id: G-C62RW4T3NH

# Starting time
start_time:          '2024-04-17T00:00:00Z' 